### ISSUE TITLE
Composition should "fix" import order

### ISSUE THREAD

**Issue by axelboc** [privatenumber/vite-css-modules#7]
### Problem

This plugin definitely fixes a number of composition issues I had, thank you!! 🥳 

However, I still have a few occurrences of composed styles appearing _after_, and overriding, the styles that compose them. This seems to be caused by the order in which components are imported. I have made a repro to demonstrate: swapping the two component imports in `main.jsx` fixes the issue.

### Expected behavior

Controlling the import order of components is not practical, so I feel like composition of styles should not be affected by import order.

But maybe that's just not possible... Maybe I'm doing things wrong and `World.module.css` should not compose styles from `Hello.module.css` but from a module shared between those two components? I've tried this in the repro and it does solve the issue. If this is the only solution, maybe it should be documented somewhere?

### Minimal reproduction URL

https://stackblitz.com/edit/vitejs-vite-15bgs7?file=src%2Fmain.jsx

### Version

Vite 5.1.0, vite-css-modules 1.4.2

### Node.js version

20.11.1

### Package manager

pnpm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
I don't think this is a bug in the plugin. Seems this is out of scope by the CSS Modules spec: https://github.com/css-modules/css-modules/issues/156

The CSS Module styles are inserted as they're imported, and when the selectors are equally "specific", [the declaration order is what determines which takes precedent](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#how_scope_blocks_affect_specificity:~:text=The%20%3Ch1%3E%20elements,vs.%20inherited%20styles).

The most resilient solution would be to increase the specificity of your selectors.

**Comment by privatenumber** [comment]
Seems like you can use https://developer.mozilla.org/en-US/docs/Web/CSS/@layer to declare CSS class order

**Comment by axelboc** [comment]
Yeah probably the cleanest workaround (compared to using more specific selectors) but browser support is a concern in my case. I could also see this getting a bit messy/difficult to manage like `z-index`. :sweat_smile: 

I've decided to document and implement a guideline that forbids composing from another component's CSS Module. If composition is needed, the base styles have to be moved to a "utility" CSS Module that must never be imported from JS:

```css
/* utils.module.css (never imported directly) */
.baseBtn {
  color: blue;
}

/* OtherComponent.module.css (imported from `OtherComponent.jsx`) */
.otherBtn {
  composes: baseBtn from './utils.module.css';
}

/* ThisComponent.module.css (imported from `ThisComponent.jsx`) */
.thisBtn {
  composes: baseBtn from './utils.module.css'; /* and not from `OtherComponent.module.css`! */
  color: red;
}
```
